var emptyFunction = require('./empty-function')
emptyFunction.default = emptyFunction;
emptyFunction.noop = emptyFunction;
emptyFunction.emptyFunction = emptyFunction;
emptyFunction.emptyFunctionReturnsTrue = require('./empty-function-returns-true');
emptyFunction.emptyFunctionReturnsFalse = require('./empty-function-returns-false');
emptyFunction.emptyFunctionReturnsNull = require('./empty-function-returns-null');
emptyFunction.emptyFunctionReturnsThis = require('./empty-function-returns-this');
emptyFunction.emptyFunctionReturnsArgument = require('./empty-function-returns-argument');
module.exports = emptyFunction;